# .___  _                     .                     .       __               .        _
# /   \ /        ___  , __   _/_     __.  , _ , _   /       |    __.  .___   |     ___/   ____
# |,_-' |,---.  /   ` |'  `.  |    .'   \ |' `|' `. |       |  .'   \ /   \  |    /   |  (
# |     |'   ` |    | |    |  |    |    | |   |   | |  /\   /  |    | |   '  |   ,'   |  `--.
# /     /    | `.__/| /    |  \__/  `._.' /   '   / |,'  \,'    `._.' /     /\__ `___,' \___.'

# Should PW run an update check from the Spigot page on startup?
run-update-checker: true

#What is the spawn world for the server? If the player hasn't played before this is the world that
#they will go to.
spawn-world: world

#Should players respawn at the world spawn if they don't have a bed?
respawn-world: true

#Should worlds deleted be moved to an archive folder in deletedworlds?
delete-archive: true

#Should worlds be automatically backed up to the backup folder?
backup-scheduler: true

#The time, in seconds, to back up every PhantomWorlds-managed world.
backup-delay: 600

# Do not touch anything here unless you know what you are doing.
advanced:
  file-version: 2
  generated-with: '${project.version}'